-- Idempotent Phase 3.1 authority content.
-- Seed-controlled records are identified by project_id + section/metric/diagram key,
-- mentorship record_key, and the six site-setting keys below. No unrelated rows are deleted.

-- Replace one unsupported percentage in the Phase 1 seed with a cautious,
-- evidence-aligned statement. The predicate targets only the original seeded row.
update public.experience_highlights
set content = 'Built a real-time integration layer between legacy systems and ERPNext using Laravel and React.js, reducing repetitive manual work.'
where experience_id = '10000000-0000-4000-8000-000000000002'
  and content = 'Built a real-time integration layer between legacy systems and ERPNext using Laravel and React.js, reducing manual work by up to 80%.';

insert into public.project_case_study_sections (project_id, section_key, section_type, title, content, is_public, sort_order)
values
-- Centralized Enterprise BFF
('20000000-0000-4000-8000-000000000001','executive-summary','summary','Executive Summary','Designed and led the implementation of a centralized backend-for-frontend architecture connecting HR, Sales, Web E-commerce, Flutter Mobile Apps V2, and IT Monitoring platforms with ERPNext/Frappe as the operational source of truth.',true,0),
('20000000-0000-4000-8000-000000000001','project-context','context','Context','Multiple applications required consistent access to ERP-backed business processes. Direct integration from every application would increase coupling, duplicate shared logic, create inconsistent error handling, and place excessive responsibility on the ERP layer.',true,1),
('20000000-0000-4000-8000-000000000001','engineering-challenge','challenge','Engineering Challenge','Create a shared backend layer that could standardize access across five consuming platforms while protecting the ERP core and remaining maintainable as business workflows evolved.',true,2),
('20000000-0000-4000-8000-000000000001','operating-constraints','constraint','Constraints','ERP remained the source of truth; five platforms had different client requirements; existing workflows could not be disrupted; security and validation needed central control; the BFF itself became a critical dependency.',true,3),
('20000000-0000-4000-8000-000000000001','role-responsibility','responsibility','Role and Responsibility','Owned architecture, service design, API standards, authentication and validation strategy, error contracts, orchestration patterns, production readiness, infrastructure coordination, cross-team alignment, and technical escalation.',true,4),
('20000000-0000-4000-8000-000000000001','technical-approach','approach','Technical Approach','Implemented a Golang Gin integration boundary with centralized request validation, shared authentication behavior, standardized responses and errors, rate limiting, server-side orchestration, controlled ERP access, reusable service patterns, and observability and fallback considerations.',true,5),
('20000000-0000-4000-8000-000000000001','key-decisions','decision','Key Decisions','Prevent direct client-to-ERP coupling, centralize cross-platform behavior, keep orchestration server-side, reject malformed or excessive requests before ERP, standardize contracts, and treat BFF availability as an operational concern.',true,6),
('20000000-0000-4000-8000-000000000001','trade-offs','tradeoff','Trade-offs','The architecture reduced duplication and coupling but increased the importance of BFF availability, monitoring, operational discipline, careful service boundaries, and shared infrastructure ownership.',true,7),
('20000000-0000-4000-8000-000000000001','delivery-coordination','coordination','Delivery and Coordination','Coordinated application, ERP, and infrastructure concerns across consuming teams so shared contracts, rollout expectations, and production responsibilities remained aligned.',true,8),
('20000000-0000-4000-8000-000000000001','outcomes','outcome','Outcome','Established a shared integration foundation for five business platforms, reduced direct application pressure on ERP, standardized validation, authentication, errors, and API behavior, and created a controlled orchestration boundary.',true,9),
('20000000-0000-4000-8000-000000000001','confidentiality-note','confidentiality','Confidentiality Note','Selected implementation details, internal topology, credentials, network configuration, monitoring data, and business rules are intentionally omitted.',true,10),
-- ATM Bersama reconciliation
('20000000-0000-4000-8000-000000000002','executive-summary','summary','Executive Summary','Contributed to the development of a Golang-based transaction reconciliation system for Artajasa''s ATM Bersama network.',true,0),
('20000000-0000-4000-8000-000000000002','project-context','context','Context','Financial transaction records from separate sources require consistent comparison and reconciliation to identify mismatches and support operational review.',true,1),
('20000000-0000-4000-8000-000000000002','engineering-challenge','challenge','Engineering Challenge','Support reliable transaction matching, discrepancy handling, reconciliation operations, and reporting in a sensitive financial systems environment.',true,2),
('20000000-0000-4000-8000-000000000002','operating-constraints','constraint','Constraints','The work required financial accuracy, careful handling of sensitive data, auditability, confidentiality, and production-oriented reliability.',true,3),
('20000000-0000-4000-8000-000000000002','role-responsibility','responsibility','Role and Responsibility','Contributed backend transaction-processing logic, data comparison workflows, discrepancy identification, reporting support, and production-oriented implementation. This does not imply ownership of the complete network or platform.',true,4),
('20000000-0000-4000-8000-000000000002','outcomes','outcome','Outcome','Supported reconciliation workflows, mismatch identification, and reporting processes while gaining experience inside a production financial system context.',true,5),
('20000000-0000-4000-8000-000000000002','confidentiality-note','confidentiality','Confidentiality Note','Transaction data, internal architecture, settlement procedures, customer identifiers, credentials, financial values, and operational workflows are intentionally omitted.',true,6),
-- Smart Sales Platform
('20000000-0000-4000-8000-000000000003','executive-summary','summary','Executive Summary','Designed and delivered a Next.js internal platform that makes ERP-backed sales workflows more accessible to operational users.',true,0),
('20000000-0000-4000-8000-000000000003','project-context','context','Context','Operational users needed to complete complex ERP-backed sales work without navigating implementation-oriented ERP interfaces and repetitive manual steps.',true,1),
('20000000-0000-4000-8000-000000000003','engineering-challenge','challenge','Engineering Challenge','Translate complex ERP workflows into a focused product experience while preserving business rules and reliable integration boundaries.',true,2),
('20000000-0000-4000-8000-000000000003','role-responsibility','responsibility','Role and Responsibility','Owned application architecture and delivery, coordinated centralized backend dependencies, aligned workflow behavior with operational stakeholders, and prepared the platform for production use.',true,3),
('20000000-0000-4000-8000-000000000003','technical-approach','approach','Technical Approach','Used Next.js and TypeScript for task-focused interfaces, centralized backend integration for controlled ERP access, and workflow automation to remove avoidable repetitive operations.',true,4),
('20000000-0000-4000-8000-000000000003','delivery-coordination','coordination','Delivery and Coordination','Worked across application, backend, ERP, and operational stakeholders to turn business processes into understandable product workflows.',true,5),
('20000000-0000-4000-8000-000000000003','outcomes','outcome','Outcome','Created a more approachable path into ERP-backed sales operations and reduced repetitive interaction without publishing unsupported financial claims.',true,6),
('20000000-0000-4000-8000-000000000003','confidentiality-note','confidentiality','Confidentiality Note','Client names, business rules, private URLs, internal screens, and implementation details are intentionally omitted.',true,7),
-- Mobile Apps V2
('20000000-0000-4000-8000-000000000004','executive-summary','summary','Executive Summary','Led the architecture and delivery of a second-generation Flutter application connected to centralized enterprise services.',true,0),
('20000000-0000-4000-8000-000000000004','project-context','context','Context','The product required modernization across application structure, user interface implementation, backend integration, authentication, and the Android and iOS release lifecycle.',true,1),
('20000000-0000-4000-8000-000000000004','engineering-challenge','challenge','Engineering Challenge','Deliver one cross-platform application while managing backend dependencies, release readiness, platform-specific requirements, and production coordination.',true,2),
('20000000-0000-4000-8000-000000000004','role-responsibility','responsibility','Role and Responsibility','Owned application architecture, Flutter UI implementation, API integration, authentication, release readiness, backend dependency coordination, and Android and iOS delivery.',true,3),
('20000000-0000-4000-8000-000000000004','technical-approach','approach','Technical Approach','Used a shared Flutter codebase with explicit service boundaries, centralized API integration, authentication handling, and release-oriented validation across supported platforms.',true,4),
('20000000-0000-4000-8000-000000000004','delivery-coordination','coordination','Delivery and Coordination','Coordinated application, backend, platform, and operational dependencies through build validation, release preparation, and production handoff.',true,5),
('20000000-0000-4000-8000-000000000004','outcomes','outcome','Outcome','Established a modernized cross-platform delivery path for Android and iOS with centralized enterprise-service integration.',true,6),
('20000000-0000-4000-8000-000000000004','confidentiality-note','confidentiality','Confidentiality Note','Private application screens, business workflows, service topology, credentials, and release internals are intentionally omitted.',true,7),
-- Smart Courier AI
('20000000-0000-4000-8000-000000000005','executive-summary','summary','Executive Summary','Built an experimental intelligent courier navigation simulation combining classical pathfinding, machine learning, neural networks, map data, and decision algorithms.',true,0),
('20000000-0000-4000-8000-000000000005','project-context','context','Context','The project explores how route graphs, weather conditions, and courier state can feed several decision techniques and produce explainable route and energy outputs.',true,1),
('20000000-0000-4000-8000-000000000005','engineering-challenge','challenge','Engineering Challenge','Compare classical search and learned prediction techniques inside one understandable simulation without presenting the experiment as a commercial logistics product.',true,2),
('20000000-0000-4000-8000-000000000005','technical-approach','approach','Technical Approach','Combined BFS and A* routing, OpenStreetMap visualization, weather-aware risk inputs, an energy prediction model, a neural-network exercise, and Minimax with alpha-beta pruning in Streamlit.',true,3),
('20000000-0000-4000-8000-000000000005','key-decisions','decision','Key Decisions','Keep classical routing outputs comparable, make model inputs visible, separate route selection from energy estimation, and present the result as an educational system experiment.',true,4),
('20000000-0000-4000-8000-000000000005','trade-offs','tradeoff','Trade-offs','The integrated simulation increases educational breadth but does not substitute for production logistics data, field validation, or commercial routing constraints.',true,5),
('20000000-0000-4000-8000-000000000005','outcomes','outcome','Outcome','Produced a working comparison surface for route selection, risk context, energy estimates, decision logic, and map visualization.',true,6),
('20000000-0000-4000-8000-000000000005','lessons-learned','lesson','Lessons Learned','Classical algorithms and machine-learning models answer different parts of the routing problem; useful systems make those boundaries and assumptions visible.',true,7),
-- Multi-School LMS
('20000000-0000-4000-8000-000000000006','executive-summary','summary','Executive Summary','Delivered full-stack learning management systems supporting multiple schools, user roles, learning content, assignments, assessments, academic workflows, and administration.',true,0),
('20000000-0000-4000-8000-000000000006','project-context','context','Context','Different school workflows needed a coherent platform model for teaching, learning, assessment, and administration without disclosing school identities or student data.',true,1),
('20000000-0000-4000-8000-000000000006','engineering-challenge','challenge','Engineering Challenge','Represent several user roles and connected academic workflows while keeping application behavior maintainable across school contexts.',true,2),
('20000000-0000-4000-8000-000000000006','role-responsibility','responsibility','Role and Responsibility','Contributed end-to-end delivery across Laravel backend work, Vue.js interfaces, MySQL data modeling, API integration, workflow implementation, and release support.',true,3),
('20000000-0000-4000-8000-000000000006','technical-approach','approach','Technical Approach','Structured role-aware application workflows around learning content, assignments, assessments, academic operations, and administration using Laravel, Vue.js, MySQL, and APIs.',true,4),
('20000000-0000-4000-8000-000000000006','outcomes','outcome','Outcome','Delivered usable education platforms across multiple school contexts without publishing unsupported student counts or institutional identities.',true,5),
('20000000-0000-4000-8000-000000000006','confidentiality-note','confidentiality','Confidentiality Note','School names, student information, private screens, credentials, and institution-specific workflows are intentionally omitted.',true,6)
on conflict (project_id, section_key) do update set section_type=excluded.section_type, title=excluded.title, content=excluded.content, is_public=excluded.is_public, sort_order=excluded.sort_order;

insert into public.project_metrics (project_id, metric_key, label, value, context, is_public, sort_order)
values
('20000000-0000-4000-8000-000000000001','connected-platforms','Connected Platforms','5','HR, Sales, Web E-commerce, Mobile Apps V2, and IT Monitoring',true,0),
('20000000-0000-4000-8000-000000000001','shared-integration-layer','Shared Integration Layer','1','Centralized Golang Gin BFF',true,1),
('20000000-0000-4000-8000-000000000004','supported-platforms','Supported Platforms','Android + iOS','Cross-platform Flutter delivery',true,0)
on conflict (project_id, metric_key) do update set label=excluded.label, value=excluded.value, context=excluded.context, is_public=excluded.is_public, sort_order=excluded.sort_order;

insert into public.project_diagrams (project_id, diagram_key, title, description, diagram_type, diagram_data, text_alternative, is_public, sort_order)
values
('20000000-0000-4000-8000-000000000001','public-system-boundary','Public System Architecture','Sanitized relationship map showing platform clients, shared controls, the BFF boundary, and the ERP core.','architecture',
'{"groups":[{"id":"clients","label":"Client Platforms"},{"id":"controls","label":"Shared Controls"},{"id":"core","label":"Enterprise Core"}],"nodes":[{"id":"hr","label":"HR","group":"clients"},{"id":"sales","label":"Sales","group":"clients"},{"id":"web-commerce","label":"Web E-commerce","group":"clients"},{"id":"mobile-v2","label":"Mobile Apps V2","group":"clients"},{"id":"it-monitoring","label":"IT Monitoring","group":"clients"},{"id":"bff","label":"Golang Gin BFF","group":"controls","description":"Central orchestration boundary"},{"id":"authentication","label":"Authentication","group":"controls"},{"id":"validation","label":"Validation","group":"controls"},{"id":"rate-limiting","label":"Rate Limiting","group":"controls"},{"id":"orchestration","label":"Orchestration","group":"controls"},{"id":"errors","label":"Error Standardization","group":"controls"},{"id":"observability","label":"Observability","group":"controls"},{"id":"erp","label":"ERPNext / Frappe","group":"core"},{"id":"enterprise-services","label":"Data, Workflows & Operational Services","group":"core"}],"edges":[{"from":"hr","to":"bff","label":"Validated request"},{"from":"sales","to":"bff"},{"from":"web-commerce","to":"bff"},{"from":"mobile-v2","to":"bff"},{"from":"it-monitoring","to":"bff"},{"from":"bff","to":"erp","label":"Controlled integration"},{"from":"erp","to":"enterprise-services","label":"Operational source of truth"}]}'::jsonb,
'Five client platforms connect to a centralized Golang Gin BFF. The BFF applies authentication, validation, rate limiting, orchestration, error standardization, and observability before controlled integration with ERPNext/Frappe and its data, workflows, and operational services.',true,0),
('20000000-0000-4000-8000-000000000005','decision-pipeline','Experimental Decision Pipeline','Public architecture for the educational routing simulation.','flow',
'{"groups":[{"id":"inputs","label":"Inputs"},{"id":"decisions","label":"Decision Systems"},{"id":"outputs","label":"Outputs"}],"nodes":[{"id":"route-graph","label":"Route Graph","group":"inputs"},{"id":"weather","label":"Weather Conditions","group":"inputs"},{"id":"courier-state","label":"Courier State","group":"inputs"},{"id":"bfs","label":"BFS","group":"decisions"},{"id":"a-star","label":"A*","group":"decisions"},{"id":"energy-model","label":"Energy Prediction Model","group":"decisions"},{"id":"minimax","label":"Minimax Decision Logic","group":"decisions"},{"id":"selected-route","label":"Selected Route","group":"outputs"},{"id":"risk-summary","label":"Risk Summary","group":"outputs"},{"id":"energy-estimate","label":"Energy Estimate","group":"outputs"},{"id":"map-view","label":"Map Visualization","group":"outputs"}],"edges":[{"from":"route-graph","to":"bfs"},{"from":"route-graph","to":"a-star"},{"from":"weather","to":"a-star"},{"from":"courier-state","to":"energy-model"},{"from":"courier-state","to":"minimax"},{"from":"bfs","to":"selected-route"},{"from":"a-star","to":"selected-route"},{"from":"weather","to":"risk-summary"},{"from":"energy-model","to":"energy-estimate"},{"from":"minimax","to":"map-view"}]}'::jsonb,
'Route graph, weather conditions, and courier state feed BFS, A-star, an energy prediction model, and Minimax decision logic. Outputs include a selected route, risk summary, energy estimate, and map visualization.',true,0)
on conflict (project_id, diagram_key) do update set title=excluded.title, description=excluded.description, diagram_type=excluded.diagram_type, diagram_data=excluded.diagram_data, text_alternative=excluded.text_alternative, is_public=excluded.is_public, sort_order=excluded.sort_order;

insert into public.mentorship_records (record_key, title, category, summary, method, outcome, is_public, sort_order)
values
('candidate-assessment','Candidate Assessment','candidate-assessment','Evaluated technical candidates beyond surface-level syntax knowledge by considering engineering judgment, role fit, ownership, learning ability, and practical execution.','Used work-sample discussion, reasoning questions, delivery scenarios, and role-specific technical review without recording private identities or confidential hiring feedback.','Several referred candidates were later described by colleagues as useful, competent, and effective contributors.',true,0),
('private-mentorship','Private Mentorship','private-mentorship','Privately mentored high-potential junior developers who had not yet reached their practical capability.','Focused on technical fundamentals, debugging, implementation discipline, project execution, professional judgment, and career positioning.',null,true,1),
('intern-development','Intern Development','intern-development','Developed software engineering interns through task ownership, implementation review, technical guidance, and delivery accountability.','Assigned bounded production-oriented work, reviewed implementation decisions, and used structured feedback to increase independent ownership.',null,true,2)
on conflict (record_key) do update set title=excluded.title, category=excluded.category, summary=excluded.summary, method=excluded.method, outcome=excluded.outcome, is_public=excluded.is_public, sort_order=excluded.sort_order;

insert into public.site_settings (key, value)
values
('professional_identity','{"professionalName":"Akbar A.R. Antapradja","fullName":"Akbar Aulia Ramadhan","title":"Principal Full-Stack & Systems Engineer","secondaryIdentity":"Builder of Systems & People"}'::jsonb),
('hero','{"name":"Akbar Aulia Ramadhan","title":"Principal Full-Stack & Systems Engineer","headline":"Building systems, teams, and operational capability across software, integration, automation, and infrastructure.","description":"I design and deliver business-critical systems across Golang backends, Next.js applications, Flutter products, ERP integration, automation, and production infrastructure—while developing the people and teams responsible for operating them."}'::jsonb),
('social_links','{"github":null,"linkedin":null}'::jsonb),
('resume','{"url":null}'::jsonb),
('authority_framework','{"builderStatement":"Building systems is only half of engineering leadership. The other half is building the people capable of owning, improving, and operating them.","systems":"I design systems that connect business processes, applications, infrastructure, and operational teams. My work spans frontend, backend, mobile, ERP, automation, and production environments.","people":"I identify technical potential beyond surface-level knowledge, develop junior talent through practical ownership and structured feedback, and help place people where they can become effective contributors.","execution":"I take responsibility for delivery across technical and organizational boundaries, coordinating developers, infrastructure personnel, vendors, and stakeholders until systems are ready for production use.","recruiterCta":"Inspect the selected systems record, review the engineering timeline, download the current resume, or start a direct conversation.","incident":{"title":"Unauthorized Crypto-Mining Incident Remediation","summary":"Resolved an unauthorized crypto-mining infrastructure incident that had driven CPU utilization to approximately 100%, reducing utilization to approximately 5% through root-cause analysis, containment, remediation, security hardening, and improved operational controls.","metricLabel":"CPU Utilization","metricValue":"~100% → ~5%","metricContext":"After remediation and hardening"}}'::jsonb),
('contact_profile','{"email":null,"location":"Bogor, Indonesia","availability":"Open to remote and international opportunities"}'::jsonb)
on conflict (key) do update set value=excluded.value;
