"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { deleteCaseStudySectionAction, reorderProjectAuthorityAction, saveCaseStudySectionAction } from "@/lib/actions/authority";
import { caseStudySectionTypes } from "@/lib/validation/authority";
import type { ActionResult } from "@/types/action";
import type { ProjectCaseStudySectionRow } from "@/types/database";
import { AuthorityResult, FieldError, authorityInputClass } from "./authority-editor-utils";
import { ReorderControls } from "./reorder-controls";
import { VisibilityBadge } from "./visibility-badge";

function SectionForm({ projectId, item }: { projectId:string; item?:ProjectCaseStudySectionRow }) { const router=useRouter(); const[pending,startTransition]=useTransition(); const[result,setResult]=useState<ActionResult|null>(null); return <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);startTransition(async()=>{const response=await saveCaseStudySectionAction(item?.id??null,{projectId,sectionKey:String(data.get("sectionKey")),sectionType:String(data.get("sectionType")) as ProjectCaseStudySectionRow["section_type"],title:String(data.get("title")),content:String(data.get("content")),isPublic:data.get("isPublic")==="on",sortOrder:Number(data.get("sortOrder"))});setResult(response);if(response.success)router.refresh();});}}><label className="text-sm">Key<input name="sectionKey" defaultValue={item?.section_key} className={authorityInputClass}/><FieldError result={result} name="sectionKey"/></label><label className="text-sm">Type<select name="sectionType" defaultValue={item?.section_type??"summary"} className={authorityInputClass}>{caseStudySectionTypes.map((type)=><option key={type}>{type}</option>)}</select></label><label className="text-sm md:col-span-2">Title<input name="title" defaultValue={item?.title} className={authorityInputClass}/><FieldError result={result} name="title"/></label><label className="text-sm md:col-span-2">Content<textarea name="content" defaultValue={item?.content} rows={7} className={authorityInputClass}/><FieldError result={result} name="content"/></label><label className="text-sm">Sort order<input name="sortOrder" type="number" min="0" defaultValue={item?.sort_order??0} className={authorityInputClass}/></label><label className="flex items-center gap-2 self-end py-2 text-sm"><input name="isPublic" type="checkbox" defaultChecked={item?.is_public}/> Explicitly public</label><div className="md:col-span-2"><AuthorityResult result={result}/></div><button disabled={pending} className="w-fit rounded bg-slate-900 px-4 py-2 text-sm text-white disabled:opacity-50">{pending?"Saving…":"Save section"}</button></form>; }

export function CaseStudySectionEditor({ projectId, items }: { projectId:string; items:ProjectCaseStudySectionRow[] }) { const router=useRouter(); const ordered=[...items].sort((a,b)=>a.sort_order-b.sort_order); async function move(index:number,direction:-1|1){const next=[...ordered];[next[index],next[index+direction]]=[next[index+direction],next[index]];await reorderProjectAuthorityAction("sections",{projectId,items:next.map((item,sortOrder)=>({id:item.id,sortOrder}))});router.refresh();} return <section className="rounded-lg border bg-white p-5"><h2 className="text-lg font-semibold">Case Study</h2><p className="mt-1 text-xs text-slate-500">Only sections marked public can appear in the sanitized public view.</p><div className="mt-5 space-y-3">{ordered.map((item,index)=><details key={item.id} className="rounded-md border p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span><span className="font-medium">{item.title}</span> <span className="ml-2 text-xs text-slate-500">{item.section_type}</span></span><span className="flex items-center gap-2"><VisibilityBadge isPublic={item.is_public}/><ReorderControls index={index} count={ordered.length} onMove={(direction)=>move(index,direction)}/><button type="button" className="text-xs text-red-700" onClick={async(e)=>{e.preventDefault();if(window.confirm(`Delete ${item.title}?`)){await deleteCaseStudySectionAction(item.id);router.refresh();}}}>Delete</button></span></summary><SectionForm projectId={projectId} item={item}/></details>)}{!items.length&&<p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">No structured sections yet.</p>}</div><details className="mt-5 rounded-md border border-dashed p-4"><summary className="cursor-pointer font-medium">Add case-study section</summary><SectionForm projectId={projectId}/></details></section>; }
