"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { deleteMentorshipRecordAction, reorderMentorshipRecordsAction, saveMentorshipRecordAction } from "@/lib/actions/authority";
import type { ActionResult } from "@/types/action";
import type { MentorshipRecordRow } from "@/types/database";
import { AuthorityResult, authorityInputClass } from "./authority-editor-utils";
import { ReorderControls } from "./reorder-controls";
import { VisibilityBadge } from "./visibility-badge";

const categories=["candidate-assessment","private-mentorship","intern-development","referral","team-formation","technical-guidance"] as const;
function MentorshipForm({item}:{item?:MentorshipRecordRow}){const router=useRouter();const[pending,startTransition]=useTransition();const[result,setResult]=useState<ActionResult|null>(null);return <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);startTransition(async()=>{const response=await saveMentorshipRecordAction(item?.id??null,{recordKey:String(data.get("recordKey")),title:String(data.get("title")),category:String(data.get("category")) as MentorshipRecordRow["category"],summary:String(data.get("summary")),method:String(data.get("method")),outcome:String(data.get("outcome")),isPublic:data.get("isPublic")==="on",sortOrder:Number(data.get("sortOrder"))});setResult(response);if(response.success)router.refresh();});}}><label className="text-sm">Record key<input name="recordKey" defaultValue={item?.record_key} className={authorityInputClass}/></label><label className="text-sm">Category<select name="category" defaultValue={item?.category??categories[0]} className={authorityInputClass}>{categories.map((category)=><option key={category}>{category}</option>)}</select></label><label className="text-sm md:col-span-2">Title<input name="title" defaultValue={item?.title} className={authorityInputClass}/></label><label className="text-sm md:col-span-2">Public-safe summary<textarea name="summary" defaultValue={item?.summary} rows={5} className={authorityInputClass}/></label><label className="text-sm md:col-span-2">Method<textarea name="method" defaultValue={item?.method??""} rows={4} className={authorityInputClass}/></label><label className="text-sm md:col-span-2">Outcome<textarea name="outcome" defaultValue={item?.outcome??""} rows={3} className={authorityInputClass}/></label><label className="text-sm">Sort order<input name="sortOrder" type="number" min="0" defaultValue={item?.sort_order??0} className={authorityInputClass}/></label><label className="flex items-center gap-2 self-end py-2 text-sm"><input name="isPublic" type="checkbox" defaultChecked={item?.is_public}/> Explicitly public</label><div className="md:col-span-2"><AuthorityResult result={result}/></div><button disabled={pending} className="w-fit rounded bg-slate-900 px-4 py-2 text-sm text-white">{pending?"Saving…":"Save record"}</button></form>}
export function MentorshipRecordEditor({items}:{items:MentorshipRecordRow[]}){const router=useRouter();const ordered=[...items].sort((a,b)=>a.sort_order-b.sort_order);async function move(index:number,direction:-1|1){const next=[...ordered];[next[index],next[index+direction]]=[next[index+direction],next[index]];await reorderMentorshipRecordsAction({items:next.map((item,sortOrder)=>({id:item.id,sortOrder}))});router.refresh();}return <div className="space-y-3">{ordered.map((item,index)=><details key={item.id} className="rounded-lg border bg-white p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span><span className="font-medium">{item.title}</span><span className="ml-2 text-xs text-slate-500">{item.category}</span></span><span className="flex items-center gap-2"><VisibilityBadge isPublic={item.is_public}/><ReorderControls index={index} count={ordered.length} onMove={(direction)=>move(index,direction)}/><button type="button" className="text-xs text-red-700" onClick={async(e)=>{e.preventDefault();if(window.confirm(`Delete ${item.title}?`)){await deleteMentorshipRecordAction(item.id);router.refresh();}}}>Delete</button></span></summary><MentorshipForm item={item}/></details>)}{!items.length&&<p className="rounded-lg border bg-white p-6 text-sm text-slate-500">No mentorship records in this category.</p>}<details className="rounded-lg border border-dashed bg-white p-4"><summary className="cursor-pointer font-medium">Add mentorship record</summary><MentorshipForm/></details></div>}
