"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { deleteProjectDiagramAction, reorderProjectAuthorityAction, saveProjectDiagramAction } from "@/lib/actions/authority";
import { diagramDataSchema } from "@/lib/validation/authority";
import type { ActionResult } from "@/types/action";
import type { ProjectDiagramRow } from "@/types/database";
import { AuthorityResult, authorityInputClass } from "./authority-editor-utils";
import { DiagramNodeEditor } from "./diagram-node-editor";
import { ReorderControls } from "./reorder-controls";
import { VisibilityBadge } from "./visibility-badge";

const blankDiagram={groups:[{id:"layer",label:"Layer"}],nodes:[{id:"node",label:"Node",group:"layer"}],edges:[]};
function DiagramForm({projectId,item}:{projectId:string;item?:ProjectDiagramRow}){const router=useRouter();const[pending,startTransition]=useTransition();const[result,setResult]=useState<ActionResult|null>(null);return <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);let json:unknown;try{json=JSON.parse(String(data.get("diagramData")))}catch{return setResult({success:false,message:"Diagram JSON is not valid."})}const parsed=diagramDataSchema.safeParse(json);if(!parsed.success)return setResult({success:false,message:parsed.error.issues[0]?.message??"Diagram JSON is invalid."});startTransition(async()=>{const response=await saveProjectDiagramAction(item?.id??null,{projectId,diagramKey:String(data.get("diagramKey")),title:String(data.get("title")),description:String(data.get("description")),diagramType:String(data.get("diagramType")) as ProjectDiagramRow["diagram_type"],diagramData:parsed.data,textAlternative:String(data.get("textAlternative")),isPublic:data.get("isPublic")==="on",sortOrder:Number(data.get("sortOrder"))});setResult(response);if(response.success)router.refresh();});}}><label className="text-sm">Key<input name="diagramKey" defaultValue={item?.diagram_key} className={authorityInputClass}/></label><label className="text-sm">Type<select name="diagramType" defaultValue={item?.diagram_type??"architecture"} className={authorityInputClass}>{["flow","layered","integration","architecture","sequence-summary"].map((type)=><option key={type}>{type}</option>)}</select></label><label className="text-sm md:col-span-2">Title<input name="title" defaultValue={item?.title} className={authorityInputClass}/></label><label className="text-sm md:col-span-2">Description<textarea name="description" defaultValue={item?.description??""} rows={2} className={authorityInputClass}/></label><div className="md:col-span-2"><DiagramNodeEditor/></div><label className="text-sm md:col-span-2">Diagram JSON<textarea name="diagramData" defaultValue={JSON.stringify(item?.diagram_data??blankDiagram,null,2)} rows={16} spellCheck={false} className={`${authorityInputClass} font-mono text-xs`}/></label><label className="text-sm md:col-span-2">Accessible text alternative<textarea name="textAlternative" defaultValue={item?.text_alternative} rows={4} className={authorityInputClass}/></label><label className="text-sm">Sort order<input name="sortOrder" type="number" min="0" defaultValue={item?.sort_order??0} className={authorityInputClass}/></label><label className="flex items-center gap-2 self-end py-2 text-sm"><input name="isPublic" type="checkbox" defaultChecked={item?.is_public}/> Explicitly public</label><div className="md:col-span-2"><AuthorityResult result={result}/></div><button disabled={pending} className="w-fit rounded bg-slate-900 px-4 py-2 text-sm text-white">{pending?"Saving…":"Save diagram"}</button></form>}
export function ProjectDiagramEditor({projectId,items}:{projectId:string;items:ProjectDiagramRow[]}){const router=useRouter();const ordered=[...items].sort((a,b)=>a.sort_order-b.sort_order);async function move(index:number,direction:-1|1){const next=[...ordered];[next[index],next[index+direction]]=[next[index+direction],next[index]];await reorderProjectAuthorityAction("diagrams",{projectId,items:next.map((item,sortOrder)=>({id:item.id,sortOrder}))});router.refresh();}return <section className="rounded-lg border bg-white p-5"><h2 className="text-lg font-semibold">Architecture Diagrams</h2><p className="mt-1 text-xs text-slate-500">Public diagrams must stay sanitized and include a complete text alternative.</p><div className="mt-5 space-y-3">{ordered.map((item,index)=><details key={item.id} className="rounded-md border p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span className="font-medium">{item.title}</span><span className="flex items-center gap-2"><VisibilityBadge isPublic={item.is_public}/><ReorderControls index={index} count={ordered.length} onMove={(direction)=>move(index,direction)}/><button type="button" className="text-xs text-red-700" onClick={async(e)=>{e.preventDefault();if(window.confirm(`Delete ${item.title}?`)){await deleteProjectDiagramAction(item.id);router.refresh();}}}>Delete</button></span></summary><DiagramForm projectId={projectId} item={item}/></details>)}{!items.length&&<p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">No diagrams yet.</p>}</div><details className="mt-5 rounded-md border border-dashed p-4"><summary className="cursor-pointer font-medium">Add diagram</summary><DiagramForm projectId={projectId}/></details></section>}
