"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { deleteProjectImageRecordAction, saveProjectImageAction } from "@/lib/actions/authority";
import type { ActionResult } from "@/types/action";
import type { ProjectImageRow } from "@/types/database";
import { AuthorityResult, authorityInputClass } from "./authority-editor-utils";
import { ImageUpload } from "./image-upload";
import { VisibilityBadge } from "./visibility-badge";

function MediaForm({projectId,item}:{projectId:string;item?:ProjectImageRow}){const router=useRouter();const[url,setUrl]=useState(item?.image_url??"");const[pending,startTransition]=useTransition();const[result,setResult]=useState<ActionResult|null>(null);return <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);startTransition(async()=>{const response=await saveProjectImageAction(item?.id??null,{projectId,imageUrl:url,altText:String(data.get("altText")),caption:String(data.get("caption")),imageCategory:String(data.get("imageCategory")) as NonNullable<ProjectImageRow["image_category"]>,isPublic:data.get("isPublic")==="on",sortOrder:Number(data.get("sortOrder"))});setResult(response);if(response.success)router.refresh();});}}><div className="md:col-span-2"><ImageUpload projectId={projectId} onUploaded={setUrl}/></div><label className="text-sm md:col-span-2">Image URL<input name="imageUrl" value={url} onChange={(event)=>setUrl(event.target.value)} className={authorityInputClass}/></label><label className="text-sm md:col-span-2">Alt text<input name="altText" defaultValue={item?.alt_text??""} className={authorityInputClass}/></label><label className="text-sm md:col-span-2">Caption<textarea name="caption" defaultValue={item?.caption??""} rows={2} className={authorityInputClass}/></label><label className="text-sm">Category<select name="imageCategory" defaultValue={item?.image_category??"other"} className={authorityInputClass}>{["interface","mobile","architecture","workflow","infrastructure","report","code","documentation","other"].map((category)=><option key={category}>{category}</option>)}</select></label><label className="text-sm">Sort order<input name="sortOrder" type="number" min="0" defaultValue={item?.sort_order??0} className={authorityInputClass}/></label><label className="flex items-center gap-2 text-sm md:col-span-2"><input name="isPublic" type="checkbox" defaultChecked={item?.is_public}/> Approved for public display</label><div className="md:col-span-2"><AuthorityResult result={result}/></div><button disabled={pending} className="w-fit rounded bg-slate-900 px-4 py-2 text-sm text-white">{pending?"Saving…":"Save media"}</button></form>}
export function ProjectMediaEditor({projectId,items}:{projectId:string;items:ProjectImageRow[]}){const router=useRouter();return <section className="rounded-lg border bg-white p-5"><h2 className="text-lg font-semibold">Media Evidence</h2><p className="mt-1 text-xs text-slate-500">Uploads and existing rows remain private until the public approval checkbox is selected. Confidential projects require the same explicit approval.</p><div className="mt-5 space-y-3">{items.map((item)=><details key={item.id} className="rounded-md border p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span className="truncate font-medium">{item.caption||item.alt_text||item.image_url}</span><span className="flex items-center gap-2"><VisibilityBadge isPublic={item.is_public}/><button type="button" className="text-xs text-red-700" onClick={async(e)=>{e.preventDefault();if(window.confirm("Delete this gallery record? The stored object is retained.")){await deleteProjectImageRecordAction(item.id);router.refresh();}}}>Delete</button></span></summary><MediaForm projectId={projectId} item={item}/></details>)}{!items.length&&<p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">No gallery evidence yet.</p>}</div><details className="mt-5 rounded-md border border-dashed p-4"><summary className="cursor-pointer font-medium">Add media evidence</summary><MediaForm projectId={projectId}/></details></section>}
