"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { deleteProjectMetricAction, reorderProjectAuthorityAction, saveProjectMetricAction } from "@/lib/actions/authority";
import type { ActionResult } from "@/types/action";
import type { ProjectMetricRow } from "@/types/database";
import { AuthorityResult, FieldError, authorityInputClass } from "./authority-editor-utils";
import { ReorderControls } from "./reorder-controls";
import { VisibilityBadge } from "./visibility-badge";

function MetricForm({projectId,item}:{projectId:string;item?:ProjectMetricRow}){const router=useRouter();const[pending,startTransition]=useTransition();const[result,setResult]=useState<ActionResult|null>(null);return <form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const data=new FormData(event.currentTarget);startTransition(async()=>{const response=await saveProjectMetricAction(item?.id??null,{projectId,metricKey:String(data.get("metricKey")),label:String(data.get("label")),value:String(data.get("value")),context:String(data.get("context")),isPublic:data.get("isPublic")==="on",sortOrder:Number(data.get("sortOrder"))});setResult(response);if(response.success)router.refresh();});}}><label className="text-sm">Key<input name="metricKey" defaultValue={item?.metric_key} className={authorityInputClass}/><FieldError result={result} name="metricKey"/></label><label className="text-sm">Label<input name="label" defaultValue={item?.label} className={authorityInputClass}/></label><label className="text-sm">Value<input name="value" defaultValue={item?.value} className={authorityInputClass}/></label><label className="text-sm">Context<input name="context" defaultValue={item?.context??""} className={authorityInputClass}/></label><label className="text-sm">Sort order<input name="sortOrder" type="number" min="0" defaultValue={item?.sort_order??0} className={authorityInputClass}/></label><label className="flex items-center gap-2 self-end py-2 text-sm"><input name="isPublic" type="checkbox" defaultChecked={item?.is_public}/> Evidence verified and public</label><div className="md:col-span-2"><AuthorityResult result={result}/></div><button disabled={pending} className="w-fit rounded bg-slate-900 px-4 py-2 text-sm text-white">{pending?"Saving…":"Save metric"}</button></form>}
export function ProjectMetricEditor({projectId,items}:{projectId:string;items:ProjectMetricRow[]}){const router=useRouter();const ordered=[...items].sort((a,b)=>a.sort_order-b.sort_order);async function move(index:number,direction:-1|1){const next=[...ordered];[next[index],next[index+direction]]=[next[index+direction],next[index]];await reorderProjectAuthorityAction("metrics",{projectId,items:next.map((item,sortOrder)=>({id:item.id,sortOrder}))});router.refresh();}return <section className="rounded-lg border bg-white p-5"><h2 className="text-lg font-semibold">Metrics</h2><p className="mt-1 text-xs text-slate-500">Publish only claims supported by evidence. Do not estimate commercial or operational numbers.</p><div className="mt-5 space-y-3">{ordered.map((item,index)=><details key={item.id} className="rounded-md border p-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span className="font-medium">{item.label}: {item.value}</span><span className="flex items-center gap-2"><VisibilityBadge isPublic={item.is_public}/><ReorderControls index={index} count={ordered.length} onMove={(direction)=>move(index,direction)}/><button type="button" className="text-xs text-red-700" onClick={async(e)=>{e.preventDefault();if(window.confirm(`Delete ${item.label}?`)){await deleteProjectMetricAction(item.id);router.refresh();}}}>Delete</button></span></summary><MetricForm projectId={projectId} item={item}/></details>)}{!items.length&&<p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">No metrics published.</p>}</div><details className="mt-5 rounded-md border border-dashed p-4"><summary className="cursor-pointer font-medium">Add metric</summary><MetricForm projectId={projectId}/></details></section>}
