import { SiteSettingsForm } from "@/components/admin/site-settings-form";
import { fallbackProfile } from "@/lib/public/data";
import { getAdminAuthoritySettings } from "@/lib/services/site-settings";
import type { AuthoritySettingsInput } from "@/lib/validation/authority";
import type { Json } from "@/types/database";

function objectValue(value:Json|undefined):Record<string,Json|undefined>{return value&&typeof value==="object"&&!Array.isArray(value)?value:{}}
function text(value:Json|undefined,fallback=""){return typeof value==="string"?value:fallback}
export default async function SettingsPage(){const rows=await getAdminAuthoritySettings();const settings=new Map(rows.map((row)=>[row.key,row.value]));const identity=objectValue(settings.get("professional_identity"));const hero=objectValue(settings.get("hero"));const social=objectValue(settings.get("social_links"));const resume=objectValue(settings.get("resume"));const authority=objectValue(settings.get("authority_framework"));const contact=objectValue(settings.get("contact_profile"));const incident=objectValue(authority.incident);const initial:AuthoritySettingsInput={professionalName:text(identity.professionalName,fallbackProfile.professionalName),fullName:text(identity.fullName,fallbackProfile.name),title:text(identity.title,fallbackProfile.title),secondaryIdentity:text(identity.secondaryIdentity,fallbackProfile.secondaryIdentity),heroHeadline:text(hero.headline,fallbackProfile.heroTitle),heroDescription:text(hero.description,fallbackProfile.heroDescription),email:text(contact.email),location:text(contact.location,fallbackProfile.location),availability:text(contact.availability,fallbackProfile.availability),githubUrl:text(social.github),linkedinUrl:text(social.linkedin),resumeUrl:text(resume.url),builderStatement:text(authority.builderStatement,fallbackProfile.builderStatement),systemsPillar:text(authority.systems,fallbackProfile.systemsPillar),peoplePillar:text(authority.people,fallbackProfile.peoplePillar),executionPillar:text(authority.execution,fallbackProfile.executionPillar),recruiterCta:text(authority.recruiterCta,fallbackProfile.recruiterCta),incidentTitle:text(incident.title,fallbackProfile.incident.title),incidentSummary:text(incident.summary,fallbackProfile.incident.summary),incidentMetricLabel:text(incident.metricLabel,fallbackProfile.incident.metricLabel),incidentMetricValue:text(incident.metricValue,fallbackProfile.incident.metricValue),incidentMetricContext:text(incident.metricContext,fallbackProfile.incident.metricContext)};return <div className="space-y-6"><div><h1 className="text-2xl font-semibold">Authority Settings</h1><p className="mt-1 text-sm text-slate-500">Source of truth for public identity, positioning, recruiter flow, resume access, and incident evidence.</p></div><SiteSettingsForm initial={initial}/></div>}
