import Link from "next/link";
import { ArrowDownRight } from "lucide-react";
import type { PublicSiteProfile } from "@/lib/public/data";
import { ResumeLink } from "./resume-link";

export function Hero({ profile }: { profile: PublicSiteProfile }) {
  const records = [profile.location, profile.availability, "Systems Engineering", "Enterprise Integration", "Technical Leadership", "Infrastructure & Operations", profile.secondaryIdentity, "Professional English"];
  return <section className="relative overflow-hidden py-16 sm:py-24 lg:py-32"><div className="public-container grid gap-14 lg:grid-cols-[1.55fr_.75fr] lg:gap-16">
    <div><p className="editorial-label">{profile.title}</p><p className="mt-3 font-mono text-[.68rem] uppercase tracking-[.18em] text-[var(--accent-gold)]">{profile.secondaryIdentity}</p><h1 className="editorial-title mt-7 max-w-5xl text-[clamp(3.5rem,7.4vw,7.4rem)]">{profile.heroTitle}</h1><p className="mt-8 max-w-3xl text-base leading-8 text-[var(--text-secondary)] sm:text-lg">{profile.heroDescription}</p><div className="mt-10 flex flex-wrap gap-3"><Link href="/projects" className="focus-ring inline-flex items-center gap-2 bg-[var(--paper)] px-5 py-3 text-xs font-semibold uppercase tracking-[.1em] text-[var(--ink)] hover:bg-[var(--paper-soft)]">View selected work <ArrowDownRight size={16}/></Link><Link href="/experience" className="focus-ring inline-flex items-center px-4 py-3 text-xs uppercase tracking-[.1em] text-[var(--text-primary)] underline">Read engineering record</Link><ResumeLink url={profile.resumeUrl}/><Link href="/contact" className="focus-ring px-4 py-3 text-xs uppercase tracking-[.1em] text-[var(--text-secondary)] underline hover:text-[var(--text-primary)]">Contact me</Link></div></div>
    <aside className="technical-grid relative self-end border border-[var(--border)] bg-[var(--surface)] p-6 sm:p-8"><p className="editorial-label">Engineering dossier / 2026</p><p className="mt-8 font-serif text-4xl leading-none">{profile.professionalName}<br/><span className="text-[var(--accent-gold)]">Authority index</span></p><ol className="mt-10 grid gap-x-5 sm:grid-cols-2 lg:grid-cols-1">{records.map((record,index)=><li key={record} className="grid grid-cols-[2rem_1fr] gap-3 border-t border-[var(--border)] py-3 text-xs leading-5"><span className="font-mono text-[var(--accent-gold)]">{String(index+1).padStart(2,"0")}</span><span className="text-[var(--paper-soft)]">{record}</span></li>)}</ol></aside>
  </div></section>;
}
