import type { Metadata } from "next";
import { ContactCta } from "@/components/public/contact-cta";
import { SectionHeading } from "@/components/public/section-heading";
import { getPublicSiteProfileSafe, getPublicSkills } from "@/lib/public/data";
import { pageMetadata } from "@/lib/public/metadata";

export const metadata:Metadata=pageMetadata("About","How Akbar approaches systems engineering, technical leadership, documentation, AI-assisted delivery, and production accountability.","/about");
const records=[
  ["How I work","I decompose ambiguous requirements into operating constraints, domain boundaries, delivery stages, and verifiable outcomes. I use official documentation, source code, and AI-assisted engineering tools to accelerate implementation while remaining responsible for architecture, validation, debugging, security, and production reliability."],
  ["Engineering philosophy","The best solution is not the one with the most technology. It is the one whose boundaries, failure modes, observability, and ownership model remain understandable after launch."],
  ["Leadership & collaboration","I am comfortable coordinating developers, infrastructure personnel, vendors, project managers, and business stakeholders. Technical leadership means making decisions legible, reviewing the work, and staying accountable when systems reach production."],
  ["Current focus","Backend orchestration, enterprise integration, ERP-centered workflows, AI-assisted automation, cross-platform products, and reliable production infrastructure."],
  ["International availability","Open to remote roles, Malaysia, Singapore, Europe, and international contractor engagements where broad system ownership is valuable."],
];
export default async function AboutPage(){const[profile,skills]=await Promise.all([getPublicSiteProfileSafe(),getPublicSkills()]);const technologies=[...new Set(skills.map(skill=>skill.name))];return <><div className="public-container py-16 sm:py-24"><SectionHeading label="About the engineer" title="Systems thinking, practical delivery, accountable ownership."/><section className="paper-panel grid gap-8 p-7 sm:p-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="editorial-label !text-[var(--accent-brown)]">Professional overview</p><p className="mt-7 font-serif text-4xl leading-[1.05]">A full-stack and systems engineer who can follow a requirement from interface to infrastructure.</p></div><p className="text-base leading-8 text-[rgba(24,19,15,.72)]">My work spans frontend products, backend services, mobile delivery, ERP integration, automation, release operations, and incident response. That range helps me recognize the handoffs where complex systems usually lose clarity.</p></section><div className="mt-16 divide-y divide-[var(--border)] border-y border-[var(--border)]">{records.map(([title,content],index)=><section key={title} className="grid gap-5 py-9 md:grid-cols-[4rem_15rem_1fr]"><span className="font-mono text-xs text-[var(--accent-gold)]">0{index+1}</span><h2 className="font-serif text-3xl">{title}</h2><p className="max-w-3xl text-sm leading-7 text-[var(--text-secondary)]">{content}</p></section>)}</div><section className="mt-16"><p className="editorial-label">Technology range</p><div className="mt-6 flex flex-wrap gap-x-5 gap-y-3 border-y border-[var(--border)] py-6 font-mono text-[.68rem] uppercase tracking-[.08em] text-[var(--paper-soft)]">{technologies.map(item=><span key={item}>{item}</span>)}</div></section></div><ContactCta profile={profile}/></>}
